knowledgeShare/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from knowShareWeb.views import * 
from BigBlue.views import *
from django.views.generic import RedirectView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', main_page),
    url(r'^howto/', howto_page),
    url(r'^teacher/$', teacher_page),
    url(r'^teacherSubmit/$', teacherSubmit_page),
    url(r'^teacherInfoChange/$', teacherInfoChange_page),                    
    url(r'^student/$', student_page),
    url(r'^studentSubmit/$', studentSubmit_page),
    url(r'^lecture/$', lecture_page),
    url(r'^lectureSubmit/$', lectureSubmit_page),                      
    url(r'^contact/$', contact_page),
    url(r'^myProfile/$', my_profile_page),
    url(r'^submitList/$', submit_list_page),
    url(r'^receiveList/$', receive_list_page),
    url(r'^tempLecture/$', temp_lecture_page),
    url(r'^tempJoin/$', temp_lecture_join),


    # url(r'^knowledgeShare/', include('knowledgeShare.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^knowShareAdmin/', admin_page),
    
    # Account
    url(r'^register/$', register_page),
    url(r'^logout/$', logout_page),
    url(r'^login/$', login_page),

    # Register
    url(r'^teacherRegister/$', teacher_register_page),
    url(r'^teacherProfileChange/$', teacher_profile_change_page),
    url(r'^studentRegister/$', student_register_page),
    url(r'^lectureRegister/$', lecture_register_page),
    url(r'^studentLectureOffer/$', student_lecture_offer_page),
                       
    # Request
    url(r'^teacherRequest/$', teacher_request_page),
    url(r'^studentRequest/$', student_request_page),
    url(r'^teacherRequestPermission/$', teacher_request_permission),
    url(r'^studentRequestPermission/$', student_request_permission),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=False)),

    # BigBlue
    url(r'^createMeeting/$', create_meeting),
    url(r'^endMeeting/$', end_meeting),
    url(r'^joinMeeting/$', join_meeting),
    url(r'^isMeetingRunning/$', isMeetingRunning),
    url(r'^getMeetingInfo/$', getMeetingInfo),
    url(r'^getMeetings/$', getMeetings),

)

urlpatterns += staticfiles_urlpatterns()

knowShareWeb/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import *

# Create your models here.
class TeacherManager(models.Manager):
    def create_teacher(self, name, highschool, university, age, sex, career, money, tutorTime, tutorType, phoneNumber, user):
        teacher = self.model(name=name, highschool=highschool, university=university, age=age, sex=sex, career=career, money=money, tutorTime=tutorTime, tutorType=tutorType, phoneNumber=phoneNumber)
        teacher.user = user
        teacher.save()
        return teacher 

    def change_teacher(self, id, name, highschool, university, age, sex, career, money, tutorTime, phoneNumber, tutorType):
        teacher =  self.get(id=id)
        teacher.name = name
        teacher.highschool = highschool
        teacher.university = university
        teacher.age = age
        teacher.sex = sex
        teacher.career = career
        teacher.money = money
        teacher.tutorTime = tutorTime
        teacher.tutorType = tutorType
        teacher.phoneNumber = phoneNumber
        teacher.save()
        return teacher

class Teacher(models.Model):
    name = models.CharField(max_length = 30)
    highschool = models.CharField(max_length = 30)
    university = models.CharField(max_length = 30)
    age = models.IntegerField()
    sex = models.IntegerField()
    career = models.TextField()
    money = models.IntegerField()
    tutorTime = models.IntegerField()
    tutorType = models.IntegerField()
    phoneNumber = models.IntegerField()
    user = models.OneToOneField(User, null=True)
    objects = TeacherManager()

class TeacherAdmin(admin.ModelAdmin):
    list_display = ('name', 'highschool', 'university', 'age', 'sex', 'career', 'money', 'tutorTime', 'tutorType', 'phoneNumber',  'get_user')
    def get_user(self, obj):
        return obj.user.username
admin.site.register(Teacher, TeacherAdmin)


class StudentManager(models.Manager):
    def create_student(self, name, grade, sex, phoneNumber, user):
        student = self.model(name=name, grade=grade, sex=sex, phoneNumber=phoneNumber)
        student.user = user
        student.save()
        return student

class Student(models.Model):
    name = models.CharField(max_length = 30)
    grade = models.IntegerField()
    sex = models.IntegerField()
    phoneNumber = models.IntegerField()
    user = models.OneToOneField(User, null=True)
    objects = StudentManager()

class StudentAdmin(admin.ModelAdmin):
    list_display = ('id', 'name', 'grade', 'sex', 'phoneNumber', 'get_user')
    def get_user(self, obj):
        return obj.user.username
admin.site.register(Student, StudentAdmin)


class StudentLectureOfferManager(models.Manager):
    def create(self, money, tutorTime, comment, student):
        studentLectureOffer = self.model(money=money, tutorTime=tutorTime, comment=comment)
        studentLectureOffer.student = student
        studentLectureOffer.save()
        return studentLectureOffer;

class StudentLectureOffer(models.Model):
    money = models.IntegerField()
    tutorTime = models.IntegerField()
    comment = models.TextField()
    student= models.ForeignKey(Student)
    objects = StudentLectureOfferManager()

class StudentLectureOfferAdmin(admin.ModelAdmin):    
    list_display = ('id', 'get_student', 'money', 'tutorTime', 'comment')
    def get_student(self, obj):
        return obj.student.name
admin.site.register(StudentLectureOffer, StudentLectureOfferAdmin)

class LectureManager(models.Manager):
    def create_lecture(self, teacher, students, startDate, endDate, totalTime, spentTime):
        lecture = self.model(startDate=startDate, endDate=endDate, totalTime=totalTime, spentTime=spentTime)
        lecture.teacher = teacher
        lecture.save()
        for student in students : 
            lecture.student.add(student)
        return lecture

class Lecture(models.Model):
    teacher = models.ForeignKey(Teacher)
    student = models.ManyToManyField(Student)
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    totalTime = models.FloatField()
    spentTime = models.FloatField()
    objects = LectureManager()

class LectureAdmin(admin.ModelAdmin):
    list_display = ('startDate', 'endDate', 'totalTime', 'spentTime', 'get_teacher', 'get_students')
    def get_teacher(self, obj):
        return obj.teacher.name
    def get_students(self, obj):
        name = '';
        for student in obj.student.all():
            name = name + student.name + ' '
        return name
admin.site.register(Lecture, LectureAdmin)

class TeacherRequestManager(models.Manager):
    def create_teacher_request(self, teacher, student, comment, permission) :
        teacherRequest = self.model(comment=comment, permission=permission)
        teacherRequest.teacher = teacher 
        teacherRequest.student = student
        teacherRequest.save() 
        return teacherRequest

class TeacherRequest(models.Model):
    teacher = models.ForeignKey(Teacher)
    student = models.ForeignKey(Student)
    comment = models.TextField()
    permission = models.IntegerField()
    objects = TeacherRequestManager()

class TeacherRequestAdmin(admin.ModelAdmin):
    list_display = ('get_teacher', 'get_student', 'comment', 'permission')
    def get_teacher(self, obj):
        return obj.teacher.name
    def get_student(self, obj):
        return obj.student.name
admin.site.register(TeacherRequest, TeacherRequestAdmin)

class StudentRequestManager(models.Manager):
    def create_student_request(self, student, teacher, comment, permission) : 
        studentRequest = self.model(comment=comment, permission=permission) 
        studentRequest.teacher = teacher
        studentRequest.student = student
        studentRequest.save()
        return studentRequest
    
class StudentRequest(models.Model):
    student = models.ForeignKey(Student)
    teacher = models.ForeignKey(Teacher)
    comment = models.TextField()
    permission = models.IntegerField()
    objects = StudentRequestManager()
    
class StudentRequestAdmin(admin.ModelAdmin):
    list_display = ('get_student', 'get_teacher', 'comment', 'permission')
    def get_student(self, obj):
        return obj.student.name
    def get_teacher(self, obj):
        return obj.teacher.name
admin.site.register(StudentRequest, StudentRequestAdmin)

knowShareWeb/forms.py
from django import forms

class RegistrationForm(forms.Form):
    email = forms.EmailField()
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    passwordConfirm = forms.CharField(widget=forms.PasswordInput())

class TeacherRegistrationForm(forms.Form):
    name = forms.CharField()
    highschool = forms.CharField()
    university = forms.CharField()
    age = forms.IntegerField()
    sex = forms.IntegerField()
    

knowShareWeb/templates/.#admin.html
leejaehoon@lee-ui-MacBook-Pro-2.local.10100

knowShareWeb/templates/contact.html
{% extends "base.html" %}
{% block title %}고객센터{% endblock %}>
{% block css %}
{% endblock %}
{% block javascript %}
{% endblock %}        
{% block mainnav %}
{% endblock %}
{% block content %}        
    <h3>고객센터</h3>
    <p>저희 솔루션을 쓰시는 선생님과 학생분들 피드백 부탁드립니다.<br>
       다양한 사업 제휴 환영합니다.<br>
       대표번호 : 010-8259-1988<br>
       문의메일 : jaehoonlee88@gmail.com<br>
    </p>
    <br>
{% endblock %}    

knowShareWeb/templates/howto.html
{% extends "base.html" %}
{% block title %}홈{% endblock %}
{% block css %}
{% endblock %}
{% block javascript %}
{% endblock %}        
{% block mainnav %}
{% endblock %}
{% block content %}
<h3>StudyGate & BBB 이용방법</h3>
</br>
<h4>강의실 입장하는 방법</h4>
<img src="{{STATIC_URL}}img/KnowShare01.png"/>
<p>
  우선 회원가입하시고 로그인 하셔야 합니다. </br>
  1. 선생님 소개 바를 누릅니다. </br>
  2. 원하는 선생님의 강의실 입장 버튼을 누릅니다.
</p>
<img src="{{STATIC_URL}}img/KnowShare02.png"/>
</br>
<p>
  3. 자신의 대화명을 입력하고 강의실 입장 버튼을 눌러서 선생님 강의방에 입장하셔야 합니다. </br>  만약에 위와 같은 화면이 아닌 "강의실에 입장할 수 있는 권한이 없습니다."라고 뜰 경우 관리자와 선생님과 상의해서 권한을 획득하셔야 합니다. </br>
</p>
</br>
<h4>BBB 사용 방법</h4>
<img src="{{STATIC_URL}}img/KnowShare03.png"/>
<p>
  1. 허용 버튼을 눌르면 카메라를 사용할 수 있게 된다.</br>
  2. 다음에는 사운드 테스트 화면인데, 영어로 무슨 소리가 들린다면 Sound는 Ok! Default 바 뭔가 변화가 있다면 마이크도 동작하는 것이다. </br>Join Audio를 눌러서 오디오를 사용할 수 있게 한다.
</p>
<img src="{{STATIC_URL}}img/KnowShare05.png"/>
<p>
  1. 카메라 버튼을 누릅니다.</br>
  2. 카메라에 웹캠이 설치되어 있다면, 자신의 모습이 보이실 겁니다. 좌측 하단의 버튼을 눌르면 다른 사람에게 자신의 영상을 공유하게 됩니다.</br>
  3. 해당 화면에서 영상 공유를 한 사람들의 영상이 보이게 됩니다. </br>
</p>


</br>
<h4>BBB 기능 설명</h4>
<img src="{{STATIC_URL}}img/KnowShare04.png"/>
<p>
  강의실 화면입니다. 일단 순서대로 설명드리겠습니다.</br>
  1. 3개의 버튼이 순서대로 있습니다. 첫번째 버튼은 화면 공유를 설정합니다. 두번째 버튼은 스피커와 마이크를 설정합니다. 세번째 버튼은 카메라를 통한 화면 공유를 설정합니다.</br>
  2. 현재 강의실에 입장한 사람에 대한 화면입니다. 연필을 들고 있는 학생 문양은 현재 칠판을 편집할 수 있는 권한을 가진 사람을 의미합니다. </br>
  3. 스피커를 켠 사람들에 대한 화면입니다.</br>
  4. 비디오 화면을 공유한 사람에 대한 화면입니다. 1번에서 3번째 버튼을 클릭후 재생을 누르면 내 화면을 다른 사람과 공유하게 됩니다. 그때 공유되는 화면은 이 창에서 뜹니다.</br>
  5. 슬라이드 공유 화면입니다. </br>
  6. 채팅창 화면입니다. </br>
</p>

<img src="{{STATIC_URL}}img/KnowShare06.png"/>
<p>
  슬라이드 공유 화면만 확대해 놓은 부분입니다. 주요기능은 다음과 같습니다.</br>
  1. 강의자료를 올리는 부분입니다. PPTX와 PDF를 지원합니다.</br>
  2. 강의자료 슬라이드를 넘기거나 앞으로 가는 부분입니다.</br>
  3. 강의자료 슬라이드를 확대하거나 축소하는 부분입니다.</br>
  4. 좌측의 두버튼은 슬라이드 크기에 맞게 세로 맞춤, 전체크기 맞춤을 해줍니다. 우측 버튼을 누르면 5번과 같은 슬라이드 편집바가 생깁니다.</br>
  5. 연필, 사각형, 원형, 모두 되돌리기, 되돌리기, 연필 색깔, 연필 두께 순으로 기능이 정렬되어 있습니다. 필요한 기능을 선택하셔서 슬라이드를 꾸미시면 됩니다. </br>
</p>
<!--FOOTER-->

{% endblock %}    

knowShareWeb/templates/index.html
{% extends "base.html" %}
{% block title %}홈{% endblock %}
{% block css %}
{% endblock %}
{% block javascript %}
{% endblock %}        
{% block mainnav %}
{% endblock %}
{% block content %}
<h3>StudyGate 란?</h3>
<p>선생님과 학생 사이에 온라인 과외를 제공하는 서비스입니다.<br>
  StudyGate는 수요가 부족한 지역에 위치한 우수 공대생들과 공급이 부족한 지방의 학생들을 연결해주는 비타민 역할을 합니다.
</p>

<!--
<div style="width:640px; margin: 0 auto;">
<iframe width="640" height="360" 
	src="http://www.youtube.com/embed/6neFBuna9Lw?feature=player_detailpage" frameborder="0" allowfullscreen>
</iframe>
</div>
-->

<!--
    <h3>Knowledge Share 란?</h3>
    <p>Knowledge Share는 지식의 나눔을 효과적으로 돕는 서비스를 만드는 그룹입니다.<br>
       저희 서비스를 통해 여러 사람들이 지식을 쉽게 습득하고 널리 나누고 멀리 퍼트릴 수 있도록 도울 것 입니다.<br>
    </p>
    <br>
    <h4>화상 과외 서비스</h4>
    <p>선생님과 학생 사이에 온라인 과외를 제공하는 서비스입니다.<br>
    화상 과외 서비스는 수요가 부족한 지역에 위치한 우수 공대생들과 공급이 부족한 지방의 학생들을 연결해주는 비타민 역할을 합니다.
    </p>
    <br>
    <h4>WordBoost</h4>
    <p>쉽고 빠르게 단어를 외울 수 있는 솔루션입니다.
    </p>  
-->
{% endblock %}    

knowShareWeb/templates/myProfile.html
{% extends "base.html" %}
{% block title %}나의 프로필{% endblock %}
{% block css %}
.profile {width : 920px; margin : 0 auto;}

{% endblock %}
{% block javascript %}
{% endblock %}        
{% block mainnav %}
{% endblock %}
{% block content %}   
<h3>나의 프로필</h3>
<div id="basicProfile" class="profile"> 
<h4 style="float:left">기본정보</h5>
</br>
</br>
<p>
  ID : {{user.username}} </br>
  E-mail : {{user.email}} </br>
  {% if isTeacher or isStudent %}
  Group : 
  {% for group in user.groups.all %} 
  {% if forloop.last %}
  {{group.name}}
  {% else %}
  {{group.name}},
  {% endif %}
  {% endfor %}
  {% else %}
  {% endif %}
</p>
<button class="btn">정보 변경</button>
<button class="btn">삭제</button>
</div>

{% if isTeacherBool %}
</br>
<div id="TeacherProfile" class="profile"> 
<h4>선생님 프로필</h4> 
<p>
  이름 : {{user.teacher.name}} </br>
  나이 : {{user.teacher.age}}  </br>
  {% if user.teacher.sex == 0 %}
  성 : 남성 </br>
  {% elif user.teacher.sex == 1 %}
  성 : 여성 </br>
  {% endif %}</br>
  고등학교 : {{user.teacher.highschool}}</br>
  대학교 : {{user.teacher.university}}</br>
  경력 : </br>
  {% for career in careers %}
  {{career}}</br>
  {% endfor %}</br>
  과외 비용 : {{user.teacher.money}}만원</br>
  과외 시간 : 
  {% if user.teacher.tutorTime == 0  %}
  주 1회 1시간 </br>
  {% elif user.teacher.tutorTime == 1 %}
  주 2회 1시간 </br>
  {% elif user.teacher.tutorTime == 2 %}
  주 1회 2시간 </br>
  {% elif user.teacher.tutorTime == 3 %}
  주 2회 2시간 </br>
  {% endif %}
  과외 방법 : 
  {% if user.teacher.tutorType == 0 %}
  1 - 1 수업 </br>
  {% elif user.teacher.tutorType == 1 %}
  1 - 2 수업 </br>
  {% elif user.teacher.tutorType == 2 %}
  1 - 3 수업 </br>
  {% endif %}
</p>
<button class="btn">정보 변경</button>
<button class="btn">삭제</button>
</div>
{% endif %}

{% if isStudentBool %}
</br>
<div id="StudentProfile" class="profile">
<h4>학생 프로필 리스트</h4>
{% for student in user.student.all %}
student.name
{% endfor %}
<table class="table lectureTable">
  <tbody>
    {% for student in user.student_set.all  %}
    <tr class="body">
      <td>{{forloop.counter}}</td>
      <td>{{student.name}} 학생 수업 신청</td>
      <td>
	<button class="btn">정보 변경</button>
	<button class="btn">삭제</button>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<legend></legend>
</br>
</div>
{% endif %}

{% endblock %}    

knowShareWeb/templates/receiveList.html
{% extends "base.html" %}
{% block title %}요청 목록{% endblock %}>
{% block css %}
.lecture button { float:right; }
.lectureTable {margin:10px 0 0 0; padding:10px 0 0 0;}
th {font-size:20px;}
td:first-child {width:70%;}
td:last-child {width:9%;}
.sign {font-size:14px; margin:5px 0 0 0; float:right;}
{% endblock %}
{% block javascript %}
        function showStudentResponse(name, comment, studentID)
        {
             $("#studentCommentTitle").text(name + " 학생이 수업 요청")
             $("#studentComment").empty();
             var comments = comment.split("</br>")
             for(i = 0; i < comments.length; i++)
             {
                var commentText = $("<label>").text(comments[i]);
                $("#studentComment").append(commentText);
             }			  
             $("#studentID").val(studentID)
             $("#studentCommentModal").modal('show')
        }

        function showTeacherResponse(name, comment, studentID, teacherID)
        {
             $("#teacherCommentTitle").text(name + " 선생님에게 요청한 목록")
	     $("#teacherComment").empty();
             var comments = comment.split("</br>")
             for(i = 0; i < comments.length; i++)
             {
                var commentText = $("<label>").text(comments[i]);
                $("#teacherComment").append(commentText);
             }			  			    
             $("#uStudentID").val(studentID)
             $("#teacherID").val(teacherID)
             $("#teacherCommentModal").modal('show')
        }

        function changeStudentRequestPermission(permission)
        {
             var permissionIn = $('<input>').attr("type", "hidden").attr("name", "permission").val(permission);
             $(".studentRequestPermission").append($(permissionIn));
             document.studentRequestPermissionForm.submit();
        }

        function changeTeacherRequestPermission(permission)
        {             
             var permissionIn = $('<input>').attr("type", "hidden").attr("name", "permission").val(permission);
             $(".teacherRequestPermission").append($(permissionIn));
             document.teacherRequestPermissionForm.submit();
        }
{% endblock %}        
{% block mainnav %}
{% endblock %}
{% block content %}   
<!-- 학생 요청 목록 -->
{% if isTeacher %}
<h3>학생으로부터 요청 온 목록</h3>
<table class="table lectureTable">
  <tbody>
    {% for teacherRequest in studentRequestsToMe %}
    <tr class="body">
      <td>{{teacherRequest.student.name}}학생이 수업요청</td>
      <td><button style="float:right;" class="btn" onClick="javascript:showStudentResponse('{{teacherRequest.student.username}}', '{{teacherRequest.comment}}', {{teacherRequest.student.id}})">내용</button></td>
      
      {% if teacherRequest.permission == 0 %}
      <td><span class="label label-warning sign">미승인</span></td>
      {% elif teacherRequest.permission == 1 %}
      <td><span class="label label-success sign">승인</span></td>
      {% else %}
      <td><span class="label label-important sign">거절</span></td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% elif isStudent %}
<h3>선생님으로부터 요청 온 목록</h3>
<!-- 선생님 요청 목록 -->
<table class="table lectureTable">
  <tbody>
    {% for student in students %}
    {% for studentRequest in student.studentrequest_set.all %}
    <tr class="body">
      <td>{{studentRequest.teacher.name}} 선생님이 요청</td>
      <td><button class="btn" onClick="javascript:showTeacherResponse('{{studentRequest.teacher.name}}', '{{studentRequest.comment}}', {{studentRequest.student.id}}, {{studentRequest.teacher.id}})">내용</button></td>

      {% if studentRequest.permission == 1 %}
      <td><button style="float:right;" class="btn" onClick="location.href='../lectureSubmit?studentID={{studentRequest.student.id}}'">강의실 신청</button></td>
      {% else %} 
      <td><button style="float:right;" class="btn">강의실 대기</button></td>
      {% endif %}

      {% if studentRequest.permission == 0 %}
      <td><span class="label label-warning sign">미승인</span></td>
      {% elif studentRequest.permission == 1 %}
      <td><span class="label label-success sign">승인</span></td>
      {% else %}
      <td><span class="label label-important sign">거절</span></td>
      {% endif %}

    </tr>
    {% endfor %}
    {% endfor %}
  </tbody>
</table>
{% endif %}


<div id="studentCommentModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 id="studentCommentTitle"></h4>
  </div>
  <div class="modal-body">
    <div id="studentComment">
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-info" onClick="javascript:changeTeacherRequestPermission(1)">요청 승인</button>
    <button class="btn btn-danger" onClick="javascript:changeTeacherRequestPermission(2);">요청 거절</button>  
  </div>    
</div>

<div id="teacherCommentModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 id="teacherCommentTitle"></h4>
  </div>
  <div class="modal-body">
    <div id="teacherComment">
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-info" onClick="javascript:changeStudentRequestPermission(1)">요청 승인</button>
    <button class="btn btn-danger" onClick="javascript:changeStudentRequestPermission(2);">요청 거절</button>  
  </div>    
</div>

<form method="POST" class="teacherRequestPermission" name="teacherRequestPermissionForm" action="/teacherRequestPermission/"> {% csrf_token %}
  <input id="studentID" class="studentID" name="studentID" type="hidden">
</form>

<form method="POST" class="studentRequestPermission" name="studentRequestPermissionForm" action="/studentRequestPermission/"> {% csrf_token %}
  <input id="uStudentID" class="uStudentID" name="userStudentID" type="hidden">
  <input id="teacherID" class="teacherID" name="teacherID" type="hidden">
</form>

{% endblock %}    

knowShareWeb/templates/tempLecture.html
{% extends "base.html" %}
{% block title %}홈{% endblock %}
{% block css %}
{% endblock %}
{% block javascript %}
function stopMeetingRoom()
{
$(".lectureState").val("wantOff")
document.TempLectureForm.submit();
}
{% endblock %}        
{% block mainnav %}
{% endblock %}
{% block content %}
<form method="POST" name="TempLectureForm" action="/tempLecture/" > {% csrf_token %}
{% if opened %}
<input type="hidden" class="lectureState" name="lectureState" value="on">
<button class="btn btn-primary">화상방 입장</button>
<button type="button" class="btn btn-danger" onClick="javascript:stopMeetingRoom()">화상방 끄기</button>
<div style="margin-top:10px;" class="alert alert-success">
http://studygate.co.kr/tempJoin?name=JH&meetingID={{user.username}}
</div>
<p>
위 URL을 공유하시면 친구들도 강의실에 입장하실 수 있습니다.</br>
회의 또는 세미나 등에 자유롭게 활용 가능하십니다.
</p>
<p>
강의실 입장시 이름을 변경하시려면 name=JH를 name=[원하시는이름] 으로 변경하시면 됩니다.
</p>
{% else %}
<input type="hidden" name="lectureState" value="off">
<button class="btn btn-info">화상방 만들기</button>
{% endif %}
</form>
{% endblock %}    